# Brasil Fut App/scripts/team_map.py
"""
Maps WORLD_DB team slugs to Transfermarkt squad page parameters.
Format: slug -> (url_path, verein_id)
The squad page URL is: https://www.transfermarkt.com/{url_path}/kader/verein/{verein_id}
"""

TEAM_MAP: dict[str, tuple[str, int]] = {
    # ── BRA Série A ──────────────────────────────────────────────────────────
    'flarj':           ('clube-de-regatas-do-flamengo', 614),
    'palmeiras':       ('palmeiras', 1023),
    'atleticomg_bra':  ('atletico-mineiro', 950),
    'flurj':           ('fluminense-football-club', 10454),
    'botafogorj_bra':  ('botafogo-de-futebol-e-regatas', 7463),
    'saopaulo_bra':    ('sao-paulo-fc', 142),
    'cruzeiro_bra':    ('cruzeiro-esporte-clube', 1871),
    'bragantino_bra':  ('red-bull-bragantino', 86848),
    'bahia':           ('esporte-clube-bahia', 2157),
    'fortaleza':       ('fortaleza-esporte-clube', 9538),
    'vasco':           ('club-de-regatas-vasco-da-gama', 1390),
    'corinthians_bra': ('sport-club-corinthians-paulista', 199),
    'juventude':       ('esporte-clube-juventude', 5451),
    'internacional_bra': ('sport-club-internacional', 1465),
    'santos':          ('santos-fc', 9825),
    'gremio':          ('gremio-foot-ball-porto-alegrense', 1424),
    'atletico_goi':    ('atletico-clube-goianiense', 37394),
    'cuiaba':          ('cuiaba-esporte-clube', 57942),
    'criciuma':        ('criciumaec', 52001),
    'athletico_pr':    ('clube-atletico-paranaense', 11792),

    # ── BRA Série B ──────────────────────────────────────────────────────────
    'sport':           ('sport-club-do-recife', 2163),
    'vitoria':         ('esporte-clube-vitoria', 4866),
    'ceara_bra':       ('ceara-sporting-club', 29437),
    'avai':            ('avai-futebol-clube', 3025),
    'america_mg':      ('america-futebol-clube', 13197),
    'botafogo_sp':     ('botafogo-futebol-clube-sp', 17628),
    'crb_al':          ('crb-clube-de-regatas-brasil', 15780),
    'chapecoense':     ('associacao-chapecoense-de-futebol', 38802),
    'coritiba':        ('coritiba-football-club', 2019),
    'goias':           ('goias-esporte-clube', 2228),
    'novorizontino':   ('gremio-novorizontino', 83781),
    'operario_pr':     ('operario-ferroviario-esporte-clube', 77490),
    'paysandu':        ('paysandu-sport-clube', 5408),
    'vila_nova':       ('vila-nova-futebol-clube', 18025),
    'amazonas_fc':     ('amazonas-fc', 112388),
    'volta_redonda':   ('volta-redonda-futebol-clube', 38009),
    'remo':            ('clube-do-remo', 9564),
    'ferroviaria':     ('associacao-ferroviaria-de-esportes', 45609),
    'nautico':         ('clube-nautico-capibaribe', 2061),
    'athletic_club':   ('athletic-club-minas-gerais', 159876),

    # ── Premier League ───────────────────────────────────────────────────────
    'machestercity_ing':     ('manchester-city', 281),
    'liverpool_ing':         ('fc-liverpool', 31),
    'arsenal':               ('fc-arsenal', 11),
    'astonvilla_ing':        ('aston-villa', 405),
    'tottenhamhotspur_ing':  ('tottenham-hotspur', 148),
    'chelsea':               ('fc-chelsea', 631),
    'machester_ing':         ('manchester-united', 985),
    'newcastle_ing':         ('newcastle-united', 762),
    'fulham':                ('fc-fulham', 931),
    'brighton_ing':          ('brighton-hove-albion', 1237),
    'brentford_ing':         ('fc-brentford', 1598),
    'crystalpalace_ing':     ('crystal-palace', 873),
    'everton_ing':           ('fc-everton', 29),
    'ipswichtown_ing':       ('ipswich-town', 677),
    'leicestercity_ing':     ('leicester-city', 1003),
    'nottinghamforest_ing':  ('nottingham-forest', 703),
    'southampton_eng':       ('southampton-fc', 180),
    'westham_eng':           ('west-ham-united', 379),
    'wolverhampton_ing':     ('wolverhampton-wanderers', 543),
    'bournemouth_ing':       ('afc-bournemouth', 989),

    # ── La Liga ──────────────────────────────────────────────────────────────
    'barcelona_esp':         ('fc-barcelona', 131),
    'realmadrid_esp':        ('real-madrid', 418),
    'atleticomadrid_esp':    ('atletico-de-madrid', 13),
    'atleticobilbao_esp':    ('athletic-bilbao', 621),
    'realsociedad_esp':      ('real-sociedad', 681),
    'getafe_esp':            ('getafe-cf', 3709),
    'girona_esp':            ('girona-fc', 12321),
    'espanyol_esp':          ('rcd-espanyol-de-barcelona', 714),
    'celtadevigo_esp':       ('rc-celta-de-vigo', 940),
    'betis_esp':             ('real-betis-balompie', 150),
    'laspalmas_esp':         ('ud-las-palmas', 13596),
    'valladolid_esp':        ('real-valladolid-cf', 367),
    'leganes_esp':           ('cd-leganes', 3024),
    'osasuna_esp':           ('club-atletico-osasuna', 1024),
    'rayovallecano_esp':     ('rayo-vallecano', 1155),
    'sevilla_esp':           ('sevilla-fc', 368),
    'mallorca_esp':          ('rcd-mallorca', 237),
    'alaves_esp':            ('deportivo-alaves', 1108),
    'valencia_esp':          ('fc-valencia', 1049),
    'villarreal_esp':        ('villarreal-cf', 383),

    # ── Serie A (Italy) ───────────────────────────────────────────────────────
    'inter_it':              ('inter-mailand', 46),
    'milan_it':              ('ac-mailand', 5),
    'juventus_it':           ('juventus-turin', 506),
    'napoli_it':             ('ssc-neapel', 6195),
    'atalanta_it':           ('atalanta-bc', 800),
    'roma_it':               ('as-rom', 12),
    'lazio_it':              ('lazio-rom', 398),
    'fiorentina_ita':        ('acf-fiorentina', 430),
    'bologna_it':            ('fc-bologna', 3613),
    'torino_it':             ('fc-turin', 416),
    'monza_ita':             ('ac-monza', 9718),
    'udinese_it':            ('udinese-calcio', 410),
    'empoli_it':             ('fc-empoli', 749),
    'cagliari_it':           ('cagliari-calcio', 827),
    'genoa_it':              ('genua-cfc', 252),
    'lecce_ita':             ('us-lecce', 4566),
    'verona_ita':            ('hellas-verona', 276),
    'como_ita':              ('como-1907', 10569),
    'parma_ita':             ('parma-calcio-1913', 101),

    # ── Bundesliga ────────────────────────────────────────────────────────────
    'bayern_ale':            ('fc-bayern-munchen', 27),
    'bayerleverkusen_ale':   ('bayer-04-leverkusen', 15),
    'sttutgart_ale':         ('vfb-stuttgart', 79),
    'leipzig_ale':           ('rasenballsport-leipzig', 23826),
    'borussia_ale':          ('borussia-dortmund', 16),
    'heidenheim_ale':        ('1-fc-heidenheim-1846', 15258),
    'werderbremen_ale':      ('sv-werder-bremen', 86),
    'freiburg_ale':          ('sc-freiburg', 60),
    'augsburg_ale':          ('fc-augsburg', 167),
    'wolfsburg_ale':         ('vfl-wolfsburg', 82),
    'fsvmainz_ale':          ('1-fsv-mainz-05', 1108),
    'monchengladbach_ale':   ('borussia-monchengladbach', 23),
    'unionberlin_ale':       ('1-fc-union-berlin', 89009),
    'bochum_ale':            ('vfl-bochum-1848', 70),
    'stpauli_ale':           ('fc-st-pauli', 35),
    'holsteinkiel_ale':      ('holstein-kiel', 48),
    'eintrachtfr_ale':       ('eintracht-frankfurt', 24),
    'hoffenheim_ale':        ('tsg-1899-hoffenheim', 533),

    # ── Ligue 1 ───────────────────────────────────────────────────────────────
    'parissaintgermain_fr':  ('paris-saint-germain', 583),
    'monaco_fr':             ('as-monaco', 162),
    'lens_fr':               ('rc-lens', 826),
    'toulouse_fr':           ('toulouse-fc', 415),
    'rennes_fr':             ('stade-rennais-fc', 273),
    'auxerre_fr':            ('aj-auxerre', 1278),
    'angers_fr':             ('angers-sco', 9764),
    'reims_fr':              ('stade-de-reims', 1421),
    'nantes_fr':             ('fc-nantes', 995),
    'st_ettiene_fr':         ('as-saint-etienne', 280),
    'brest_fr':              ('stade-brestois-29', 7587),
    'lehavre_fr':            ('le-havre-ac', 1082),
    'lyon':                  ('olympique-lyonnais', 1041),
    'marseille_fr':          ('olympique-de-marseille', 244),
    'nice_fr':               ('ogc-nizza', 417),
    'lille_fr':              ('losc-lille', 1047),
    'strasbourg_fr':         ('rc-strasbourg-alsace', 667),
    'montpellier_fr':        ('montpellier-hsc', 969),
}
